# Generated by Django 2.1.5 on 2019-02-01 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRiC11', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='odi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='ball',
            name='Avg',
            field=models.IntegerField(null=True, verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='B',
            field=models.IntegerField(null=True, verbose_name='Balls'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='BBI',
            field=models.IntegerField(null=True, verbose_name='Best Bowling'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='BBM',
            field=models.IntegerField(null=True, verbose_name='Best Bowling Match'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='Econ',
            field=models.IntegerField(null=True, verbose_name='Economy'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='Inn',
            field=models.IntegerField(null=True, verbose_name='Innings'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='M',
            field=models.IntegerField(null=True, verbose_name='Matches'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='Runs',
            field=models.IntegerField(null=True, verbose_name='Runs'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='SR',
            field=models.IntegerField(null=True, verbose_name='Strike Rate'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='Wkts',
            field=models.IntegerField(null=True, verbose_name='Wickets'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='fwh',
            field=models.IntegerField(null=True, verbose_name='Fife wicket'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='twh',
            field=models.IntegerField(null=True, verbose_name='Ten wicket'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='Avg',
            field=models.IntegerField(null=True, verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='BF',
            field=models.IntegerField(null=True, verbose_name='Balls Faced'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='HS',
            field=models.IntegerField(null=True, verbose_name='High Score'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='Inn',
            field=models.IntegerField(null=True, verbose_name='Innings'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='M',
            field=models.IntegerField(null=True, verbose_name='Matches'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='NO',
            field=models.IntegerField(null=True, verbose_name='Not out'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='Runs',
            field=models.IntegerField(null=True, verbose_name='Runs'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='SR',
            field=models.IntegerField(null=True, verbose_name='Strike Rate'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='century',
            field=models.IntegerField(null=True, verbose_name='Century'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='double',
            field=models.IntegerField(null=True, verbose_name='Double Century'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='fifty',
            field=models.IntegerField(null=True, verbose_name='Fifty'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='fours',
            field=models.IntegerField(null=True, verbose_name='Fours'),
        ),
        migrations.AlterField(
            model_name='bat',
            name='sixes',
            field=models.IntegerField(null=True, verbose_name='Sixes'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ballstyle',
            field=models.IntegerField(null=True, verbose_name='Matches'),
        ),
        migrations.AlterField(
            model_name='player',
            name='batstyle',
            field=models.IntegerField(null=True, verbose_name='Matches'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth',
            field=models.IntegerField(null=True, verbose_name='Matches'),
        ),
        migrations.AlterField(
            model_name='player',
            name='born',
            field=models.IntegerField(null=True, verbose_name='Matches'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.IntegerField(null=True, verbose_name='Matches'),
        ),
        migrations.AddField(
            model_name='tt',
            name='p',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CRiC11.Player'),
        ),
        migrations.AddField(
            model_name='test',
            name='p',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CRiC11.Player'),
        ),
        migrations.AddField(
            model_name='odi',
            name='p',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CRiC11.Player'),
        ),
        migrations.AddField(
            model_name='ipl',
            name='p',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CRiC11.Player'),
        ),
    ]
