# Generated by Django 2.1.5 on 2019-02-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRiC11', '0002_auto_20190201_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipl',
            name='p',
        ),
        migrations.RemoveField(
            model_name='odi',
            name='p',
        ),
        migrations.RemoveField(
            model_name='test',
            name='p',
        ),
        migrations.RemoveField(
            model_name='tt',
            name='p',
        ),
        migrations.DeleteModel(
            name='ipl',
        ),
        migrations.DeleteModel(
            name='odi',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='tt',
        ),
    ]
