# Generated by Django 2.1.5 on 2019-02-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRiC11', '0003_auto_20190201_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M', models.IntegerField(null=True, verbose_name='Matches')),
                ('Inn', models.IntegerField(null=True, verbose_name='Innings')),
                ('NO', models.IntegerField(null=True, verbose_name='Not out')),
                ('Runs', models.IntegerField(null=True, verbose_name='Runs')),
                ('HS', models.IntegerField(null=True, verbose_name='High Score')),
                ('Avg', models.IntegerField(null=True, verbose_name='Average')),
                ('BF', models.IntegerField(null=True, verbose_name='Balls Faced')),
                ('SR', models.IntegerField(null=True, verbose_name='Strike Rate')),
                ('century', models.IntegerField(null=True, verbose_name='Century')),
                ('double', models.IntegerField(null=True, verbose_name='Double Century')),
                ('fifty', models.IntegerField(null=True, verbose_name='Fifty')),
                ('fours', models.IntegerField(null=True, verbose_name='Fours')),
                ('sixes', models.IntegerField(null=True, verbose_name='Sixes')),
            ],
        ),
        migrations.CreateModel(
            name='Bowl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='bat',
            name='Avg',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='BF',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='HS',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='Inn',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='M',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='NO',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='Runs',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='SR',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='century',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='double',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='fifty',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='fours',
        ),
        migrations.RemoveField(
            model_name='bat',
            name='sixes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p',
        ),
        migrations.AddField(
            model_name='player',
            name='Bat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='CRiC11.Bat'),
        ),
        migrations.RenameModel(
            old_name='Ball',
            new_name='BallType',
        ),
        migrations.AddField(
            model_name='bowl',
            name='iplball',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iplb', to='CRiC11.BallType'),
        ),
        migrations.AddField(
            model_name='bowl',
            name='odiball',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odib', to='CRiC11.BallType'),
        ),
        migrations.AddField(
            model_name='bowl',
            name='testball',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testb', to='CRiC11.BallType'),
        ),
        migrations.AddField(
            model_name='bowl',
            name='ttball',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttb', to='CRiC11.BallType'),
        ),
        migrations.AddField(
            model_name='bat',
            name='iplbat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iplba', to='CRiC11.BatType'),
        ),
        migrations.AddField(
            model_name='bat',
            name='odibat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odiba', to='CRiC11.BatType'),
        ),
        migrations.AddField(
            model_name='bat',
            name='testbat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testba', to='CRiC11.BatType'),
        ),
        migrations.AddField(
            model_name='bat',
            name='ttbat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttba', to='CRiC11.BatType'),
        ),
        migrations.AddField(
            model_name='player',
            name='Ball',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='CRiC11.Bowl'),
        ),
    ]
