# Generated by Django 2.1.5 on 2019-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRiC11', '0005_auto_20190201_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balltype',
            name='Avg',
            field=models.FloatField(null=True, verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='balltype',
            name='BBI',
            field=models.CharField(max_length=8, null=True, verbose_name='Best Bowling'),
        ),
        migrations.AlterField(
            model_name='balltype',
            name='BBM',
            field=models.CharField(max_length=8, null=True, verbose_name='Best Bowling Match'),
        ),
        migrations.AlterField(
            model_name='balltype',
            name='Econ',
            field=models.FloatField(null=True, verbose_name='Economy'),
        ),
        migrations.AlterField(
            model_name='balltype',
            name='SR',
            field=models.FloatField(null=True, verbose_name='Strike Rate'),
        ),
        migrations.AlterField(
            model_name='battype',
            name='Avg',
            field=models.FloatField(null=True, verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='battype',
            name='SR',
            field=models.FloatField(null=True, verbose_name='Strike Rate'),
        ),
    ]
