# Generated by Django 2.1.5 on 2019-02-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRiC11', '0006_auto_20190201_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ballstyle',
            field=models.IntegerField(null=True, verbose_name='Ball Style'),
        ),
        migrations.AlterField(
            model_name='player',
            name='batstyle',
            field=models.IntegerField(null=True, verbose_name='Bat Style'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth',
            field=models.IntegerField(null=True, verbose_name='Birth Place'),
        ),
        migrations.AlterField(
            model_name='player',
            name='born',
            field=models.IntegerField(null=True, verbose_name='Born'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.IntegerField(null=True, verbose_name='Role'),
        ),
    ]
