# Generated by Django 2.1.5 on 2019-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRiC11', '0008_auto_20190201_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='born',
            field=models.DateField(max_length=15, null=True, verbose_name='Born'),
        ),
    ]
